#!/bin/bash
# DIR is the script's location
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# Dump all databases in separate files
for DB in $(mysql -e 'show databases' -s --skip-column-names); do
    mysqldump $DB > "$DIR/$DB.sql";
done
